Feat/communication
VladislavKabral/TaxiProvider pull request #11
Opened 2024-03-27 18:32 UTC by VladislavKabral

2024-03-28 07:37 UTC, AbandonedScope requested changes

2024-03-28 07:37 UTC, AbandonedScope commented on DriverService/src/main/java/by/modsen/taxiprovider/driverservice/dto/request/DriverRatingRequestDTO.java
> +public class DriverRatingRequestDTO {
DriverRatingRequestDTO -> DriverRatingRequestDto

2024-03-28 07:37 UTC, AbandonedScope commented on DriverService/src/main/java/by/modsen/taxiprovider/driverservice/service/DriversService.java
> +                .block();
Вот это вынеси в отдельный класс, который будет отвечать за отправку запросов

2024-03-28 07:37 UTC, AbandonedScope commented on DriverService/src/main/java/by/modsen/taxiprovider/driverservice/service/DriversService.java
>                  .entityNotFoundException(String.format(DRIVER_NOT_FOUND, driverId)));
Это можно вынести в отдельный метод и переиспользовать

2024-03-28 07:37 UTC, AbandonedScope commented on PaymentService/src/main/java/by/modsen/taxiprovider/paymentservice/dto/request/RideDTO.java
> +public class RideDTO {
RideDTO -> RideDto

2024-03-28 07:37 UTC, AbandonedScope commented on PaymentService/src/main/java/by/modsen/taxiprovider/paymentservice/dto/response/BalanceResponseDTO.java
> +public class BalanceResponseDTO {
BalanceResponseDTO -> BalanceResponseDto

2024-03-28 07:37 UTC, AbandonedScope commented on PaymentService/src/main/java/by/modsen/taxiprovider/paymentservice/dto/response/DriverDTO.java
> +public class DriverDTO {
DriverDTO -> DriverDto
Посмотри и поправь и в других местах

2024-03-28 07:37 UTC, AbandonedScope commented on PaymentService/src/main/java/by/modsen/taxiprovider/paymentservice/service/payment/PaymentService.java
> +    }
Вот это должно быть в отдельном классе

2024-03-28 07:37 UTC, AbandonedScope commented on PaymentService/src/main/java/by/modsen/taxiprovider/paymentservice/service/payment/PaymentService.java
> +    }
Тоже в отдельный класс

2024-03-28 07:37 UTC, AbandonedScope commented on RidesService/src/main/java/by/modsen/taxiprovider/ridesservice/util/validation/ride/RideValidator.java
> +        }
Попробуй через Stream API это сделать
Или другим способом, но не так, как есть сейчас

2024-04-02 07:59 UTC, AbandonedScope requested changes

2024-04-02 07:59 UTC, AbandonedScope commented on DriverService/src/main/java/by/modsen/taxiprovider/driverservice/controller/driver/DriversController.java
> +    public ResponseEntity<List<DriverDto>> getDrivers() throws EntityNotFoundException {
Опять же, не List<DriverDto> а DriverListDto

2024-04-02 07:59 UTC, AbandonedScope commented on DriverService/src/main/java/by/modsen/taxiprovider/driverservice/controller/driver/DriversController.java
> +    public ResponseEntity<Page<DriverDto>> getDriversPage(@RequestParam("page") int page,
Page не возвращаем, это класс для роботы с бд, нельзя прокидывать его до контроллеров

2024-04-02 15:36 UTC, VladislavKabral commented on DriverService/src/main/java/by/modsen/taxiprovider/driverservice/controller/driver/DriversController.java
> +    public ResponseEntity<Page<DriverDto>> getDriversPage(@RequestParam("page") int page,
Уже исправил в другом PR

2024-04-04 07:46 UTC, AbandonedScope approved these changes

2024-04-07 16:44 UTC, closed without merging