Feat/ride creating development
VladislavKabral/TaxiProvider pull request #12
Opened 2024-03-27 18:46 UTC by VladislavKabral

2024-03-28 08:06 UTC, AbandonedScope requested changes

2024-03-28 08:06 UTC, AbandonedScope commented on DriverService/src/main/java/by/modsen/taxiprovider/driverservice/controller/driver/DriversController.java
> +    public ResponseEntity<List<DriverDTO>> getFreeDrivers() throws EntityNotFoundException {
List<DriverDTO> -> DriverListDto

2024-03-28 08:06 UTC, AbandonedScope commented on DriverService/src/main/java/by/modsen/taxiprovider/driverservice/controller/driver/DriversController.java
> +    @PatchMapping(value = "/{id}")
Почему?

2024-03-28 08:06 UTC, AbandonedScope commented on DriverService/src/main/java/by/modsen/taxiprovider/driverservice/service/driver/DriversService.java
> +        }
Можешь просто вернуть пустой список

2024-03-28 08:06 UTC, AbandonedScope commented on PaymentService/src/main/java/by/modsen/taxiprovider/paymentservice/util/validation/CustomerValidator.java
> +                            "'and role '" + customerDTO.getRole() + "' already exists");
Лучше использовать String.format или string.formatted

2024-03-28 08:06 UTC, AbandonedScope commented on RidesService/src/main/java/by/modsen/taxiprovider/ridesservice/service/ride/RidesService.java
> +        List<Ride> rides = ridesRepository.findByPassengerIdAndStatus(passengerId, "WAITING");
Оно вернёт null или пустой список?

2024-03-28 08:06 UTC, AbandonedScope commented on RidesService/src/main/java/by/modsen/taxiprovider/ridesservice/service/ride/RidesService.java
> +                ride.setStatus(rideDTO.getStatus());
В отдельный метод

2024-03-28 08:06 UTC, AbandonedScope commented on RidesService/src/main/java/by/modsen/taxiprovider/ridesservice/service/ride/RidesService.java
> +                ride.setStatus(rideDTO.getStatus());
В отдельный метод

2024-03-28 08:06 UTC, AbandonedScope commented on RidesService/src/main/java/by/modsen/taxiprovider/ridesservice/service/ride/RidesService.java
> +    }
В отдельный класс, отвечающий за http запросы

2024-04-01 17:31 UTC, VladislavKabral commented on RidesService/src/main/java/by/modsen/taxiprovider/ridesservice/service/ride/RidesService.java
> +        List<Ride> rides = ridesRepository.findByPassengerIdAndStatus(passengerId, "WAITING");
Пустой список

2024-04-01 17:35 UTC, VladislavKabral commented on DriverService/src/main/java/by/modsen/taxiprovider/driverservice/service/driver/DriversService.java
> +        }
Я бы хотел получать сообщение в сервисе поездок, если нет свободных водителей. Стоит обрабатывать пустой список в сервисе поездок, или лучше оставить как есть?

2024-04-01 17:44 UTC, VladislavKabral commented on DriverService/src/main/java/by/modsen/taxiprovider/driverservice/controller/driver/DriversController.java
> +    public ResponseEntity<List<DriverDTO>> getFreeDrivers() throws EntityNotFoundException {
Нужно создать класс, который будет хранить список DriverDto?

2024-04-02 07:52 UTC, AbandonedScope commented on DriverService/src/main/java/by/modsen/taxiprovider/driverservice/controller/driver/DriversController.java
> +    public ResponseEntity<List<DriverDTO>> getFreeDrivers() throws EntityNotFoundException {
Да

2024-04-02 07:52 UTC, AbandonedScope commented on DriverService/src/main/java/by/modsen/taxiprovider/driverservice/controller/driver/DriversController.java
> +    @PatchMapping(value = "/{id}")
Да, зачем ты заменил, так как было до  этого лучше

2024-04-02 15:54 UTC, VladislavKabral commented on RidesService/src/main/java/by/modsen/taxiprovider/ridesservice/service/ride/RidesService.java
> +        List<Ride> rides = ridesRepository.findByPassengerIdAndStatus(passengerId, "WAITING");
В другом PR исправлено: там проверка isEmpty()

2024-04-04 07:47 UTC, AbandonedScope approved these changes

2024-04-07 16:44 UTC, closed without merging