Refactor/global refactoring
VladislavKabral/TaxiProvider pull request #14
Opened 2024-03-27 18:57 UTC by VladislavKabral

2024-03-28 07:53 UTC, AbandonedScope requested changes
Повторяющиеся моменты не отмечал

2024-03-28 07:53 UTC, AbandonedScope commented on DriverService/src/main/java/by/modsen/taxiprovider/driverservice/controller/driver/DriversController.java
> +    public ResponseEntity<Page<DriverDTO>> getDriversPage(@RequestParam("page") int page,
Нельзя возвращать org.springframework.data.domain.Page - это класс уровня работы с данными, замени на свой дто

2024-03-28 07:53 UTC, AbandonedScope commented on DriverService/src/main/java/by/modsen/taxiprovider/driverservice/service/DriversService.java
>                  .orElseThrow(EntityNotFoundException
Вынеси в отдельный метод

2024-03-28 07:53 UTC, AbandonedScope commented on PassengerService/src/main/java/by/modsen/taxiprovider/passengerservice/controller/passenger/PassengersController.java
> +    public ResponseEntity<Page<PassengerDTO>> getPassengersPage(@RequestParam("page") int page,
Page замени на свою дто

2024-03-28 07:53 UTC, AbandonedScope commented on PassengerService/src/main/java/by/modsen/taxiprovider/passengerservice/controller/passenger/PassengersController.java
> +        return new ResponseEntity<>(passengersService.save(passengerDTO, bindingResult), HttpStatus.OK);
BindingResult?

2024-03-28 07:53 UTC, AbandonedScope commented on PaymentService/src/main/java/by/modsen/taxiprovider/paymentservice/service/payment/PaymentService.java
>              params.put("source", chargeRequestDTO.getCardToken());
amount, currency, source лучше вынести или в констаны или в enum

2024-03-28 07:53 UTC, AbandonedScope commented on PaymentService/src/main/java/by/modsen/taxiprovider/paymentservice/service/payment/PaymentService.java
> +                    .setBalance((long) Math.round(customerDTO.getBalance().floatValue() * CONVERT_COEFFICIENT))
(long) Math.round(customerDTO.getBalance().floatValue() * CONVERT_COEFFICIENT) 
Можно вынести в отдельный метод

2024-04-01 17:49 UTC, VladislavKabral commented on PassengerService/src/main/java/by/modsen/taxiprovider/passengerservice/controller/passenger/PassengersController.java
> +        return new ResponseEntity<>(passengersService.save(passengerDTO, bindingResult), HttpStatus.OK);
BindingResult нежелательно использовать?

2024-04-02 07:51 UTC, AbandonedScope commented on PassengerService/src/main/java/by/modsen/taxiprovider/passengerservice/controller/passenger/PassengersController.java
> +        return new ResponseEntity<>(passengersService.save(passengerDTO, bindingResult), HttpStatus.OK);
Да, не очень
Ты же можешь и без него здесь обойтись

2024-04-04 07:45 UTC, AbandonedScope approved these changes

2024-04-04 07:45 UTC, AbandonedScope commented on DriverService/src/main/java/by/modsen/taxiprovider/driverservice/dto/driver/DriverDTO.java
Все ...DTO -> ...Dto

2024-04-07 16:44 UTC, closed without merging