Feat/testing
VladislavKabral/TaxiProvider pull request #8
Opened 2024-03-26 15:28 UTC by VladislavKabral

2024-03-27 11:00 UTC, IvanKiselevichWork requested changes

2024-03-27 11:00 UTC, IvanKiselevichWork commented on DriverService/src/test/java/by/modsen/taxiprovider/driverservice/unit/drivers/DriversUnitTests.java
> +        when(driversService.save(any(NewDriverDTO.class), any(BindingResult.class)))
Почему тут и в других похожих местах any(NewDriverDTO.class), а не например eq(driverDto)?

2024-03-27 11:00 UTC, IvanKiselevichWork commented on DriverService/src/test/java/by/modsen/taxiprovider/driverservice/unit/drivers/DriversUnitTests.java
> +class DriversUnitTests {
Лучше тогда назвать класс DriversControllerUnitTests

2024-03-27 17:07 UTC, VladislavKabral commented on DriverService/src/test/java/by/modsen/taxiprovider/driverservice/unit/drivers/DriversUnitTests.java
> +        when(driversService.save(any(NewDriverDTO.class), any(BindingResult.class)))
Исправил

2024-03-28 19:40 UTC, IvanKiselevichWork approved these changes

2024-04-02 08:43 UTC, IvanKiselevichWork approved these changes

2024-04-02 15:25 UTC, closed without merging